##
# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT
#
# go to sleep after one hour (1*60*60*1000ms)

CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

CONFIG_ZMK_SLEEP=y

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n

CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=160
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3

CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# Mouse enable
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_BACKLIGHT=y
CONFIG_ZMK_BACKLIGHT_BRT_START=100

# Bluetooth tweaks
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# Enable display niceview gem
CONFIG_ZMK_DISPLAY=y
CONFIG_NICE_VIEW_GEM_ANIMATION=n
CONFIG_NICE_VIEW_GEM_ANIMATION_MS=9600
CONFIG_NICE_VIEW_GEM_WPM_FIXED_RANGE=n
